client_id = "e89d9fd3edfe7e45385c0628abd29287"
name = "badge-blitz-dev"
application_url = "https://localhost"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "inventory_levels/update" ]
  uri = "/webhooks/inventory_levels/update"

[access_scopes]
scopes = "write_metaobject_definitions,write_metaobjects,write_products,read_products,read_inventory"

[auth]
redirect_urls = [
  "https://kills-worker-nine-reporters.trycloudflare.com/auth/callback",
  "https://kills-worker-nine-reporters.trycloudflare.com/auth/shopify/callback",
  "https://kills-worker-nine-reporters.trycloudflare.com/api/auth/callback"
]